import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Elsie } from 'next/font/google';
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const elsie = Elsie({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-elsie',
});


// export const metadata: Metadata = {
//   metadataBase: new URL("https://tangentweekly.com/"),

//   title: "Tangent Weekly – Expert Political Analysis, Market Trends & Emerging Tech Insights",
// description: "Explore expert insights on political targeting, Supreme Court rulings, AI-powered robotaxis, NBA prospects like Cooper Flagg, youth mental health, and breakthrough cancer screening. Tangent Weekly delivers trusted analysis in politics, business, technology, health, and sports.",
// keywords:
// "social media liability laws 2025, Brazil Supreme Court tech rulings, platform accountability regulations, Uber Waymo robotaxi launch Atlanta, self-driving cars in Georgia, Cooper Flagg NBA draft 2025, top NBA prospects after LeBron, youth mental health and smartphone addiction, screen time vs addictive app use, cervical cancer screening with self-sample kits, mailed HPV test effectiveness, political targeting case, Puerto Rico politics and legal system",
//  openGraph: {
//     title: "Tangent Weekly - Breaking News, Politics & Business Analysis",
//  description: "Explore expert insights on political targeting, Supreme Court rulings, AI-powered robotaxis, NBA prospects like Cooper Flagg, youth mental health, and breakthrough cancer screening. Tangent Weekly delivers trusted analysis in politics, business, technology, health, and sports.",
//  url: "https://tangentweekly.com/",
//     siteName: "Tangent Weekly",
//     images: [
//       {
//         url: "https://tangentweekly.com/images/tangent-weekly-logo.webp",
//         width: 1200,
//         height: 630,
//         alt: "Tangent Weekly Logo",
//       },
//     ],
//     type: "website",
//   },

//   twitter: {
//     card: "summary_large_image",
//     title: "Tangent Weekly – Expert Political Analysis, Market Trends & Emerging Tech Insights",
//   description: "Explore expert insights on political targeting, Supreme Court rulings, AI-powered robotaxis, NBA prospects like Cooper Flagg, youth mental health, and breakthrough cancer screening. Tangent Weekly delivers trusted analysis in politics, business, technology, health, and sports.",
//    images: "https://tangentweekly.com/images/tangent-weekly-logo.webp",
//   },

//   alternates: {
//     canonical: "https://tangentweekly.com/",
//     languages: {
//       en: "https://tangentweekly.com/",
//       "x-default": "https://tangentweekly.com/",
//     },
//   },

//   authors: [{ name: "Cameron Ellis" }],

//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${elsie.variable}`} style={{ paddingTop: '20px' }}>
    
        {children}
        <Footer />
      </body>
    </html>
  );
}
